apiVersion: v2
name: demo-app
description: A Helm chart for deploying Fine Management System
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: postgresql
    version: 12.1.6
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: kafka
    version: 22.1.5
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled