apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationservice
  labels:
    app: notificationservice
spec:
  replicas: {{ .Values.notificationservice.replicaCount }}
  selector:
    matchLabels:
      app: notificationservice
  template:
    metadata:
      labels:
        app: notificationservice
    spec:
      containers:
      - name: notificationservice
        image: "{{ .Values.notificationservice.image.repository }}:{{ .Values.notificationservice.image.tag }}"
        args:
        - "--kafka_connection={{ .Values.notificationservice.kafkaConnection }}"
        - "--policeAddress={{ .Values.notificationservice.policeAddress }}"
---
apiVersion: v1
kind: Service
metadata:
  name: notificationservice
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: notificationservice